In [7]:
from unstructured.partition.pdf import partition_pdf


def process_file(file_path):
    file_type =file_path.split('.')[-1]
    if file_type.lower()=='pdf':
        elements=process_pdf(file_path)
        return elements
def process_pdf(file):
    elements = partition_pdf( filename=file)
    return elements

In [8]:
elements =process_file("/Users/libinvarghese/Documents/Jesna/projects/personal_finacial_assistant/plan_your_budget/data/raw/2dbddc56-6977-4ced-9777-4447dba9b247_invoice.pdf")

Warning: No languages specified, defaulting to English.

In [9]:
for element in elements:

    element_type = type(element).__name__

    print("TYPE:", element_type)

    print("TEXT:")
    print(str(element))

    print("-" * 50)

TYPE: Title
TEXT:
Tax Invoice/Bill of Supply/Cash Memo(Original for Recipient)
--------------------------------------------------
TYPE: ListItem
TEXT:
ASSPL-Amazon Seller Services Pvt. Ltd., ARIPL-Amazon Retail India Pvt. Ltd. (only where Amazon Retail India Pvt. Ltd. fulfillment center is co-located) Customers desirous of availing input GST credit are requested to create a Business account and purchase on Amazon.in/business from Business eligible offers Please note that this invoice is not a demand for paymentPage 1 of 1 Order Number: 402-6064414-6979531Invoice Number : BLR8-79575Order Date: 23.05.2026Invoice Details : KA-BLR8-179368921-2627Invoice Date : 23.05.2026Sl.NoDescriptionUnit PriceDiscountQtyNetAmountTaxRateTaxTypeTaxAmountTotalAmount1Generative AI System Design Interview (FullColour Edition) | 9355424965 ( 9789355424969 ) HSN:49011010₹1,900.00₹0.001₹1,900.000%IGST₹0.00₹1,900.000%CGST₹0.000%None₹0.000%SGST₹0.00Shipping Charges ₹79.00-₹79.00₹0.000%IGST₹0.00₹0.000%CGST₹0.000%None₹0.000%SGST₹0.00TOTAL:₹0.00₹1,900.00Amount in Words:One Thousand Nine Hundred onlyWhether tax is payable under reverse charge - NoSold By :Shroff Publishers & Distributors Pvt. Ltd. *Building 2 ( Wh 2), Plot no. 12/P2 (IT Sector),Hitech, Defence and Aerospace Park, DevanahalliBengaluru, Karnataka, 562149INPAN No: AAACS9274PGST Registration No: NotApplicableBilling Address :Jesna AugustineFlat No. 211, No. 77 East,, Phase -2, CozyhomeLayoutBENGALURU, KARNATAKA, 562125INState/UT Code: 29Shipping Address :Jesna Augustine Jesna AugustineFlat No. 211, No. 77 East,, Phase -2, CozyhomeLayoutBENGALURU, KARNATAKA, 562125INState/UT Code: 29 Place of supply: KARNATAKA Place of delivery: KARNATAKA
--------------------------------------------------
TYPE: Title
TEXT:
Tax Invoice/Bill of Supply/Cash Memo(Original for Recipient)
--------------------------------------------------
TYPE: NarrativeText
TEXT:
Please note that this invoice is not a demand for payment Regd Office: Amazon Seller Services Private Limited Sattva Horizon, Survey No 6/1 and 7/1, Vinayak Nagar, Kattigenahalli Venkatala Village, Yelahanka Hobli,Bengaluru Telephone: +91 89 33420300 Fax: +91 80 30625685 Email: customer-service@amazon.in Amazon.in - Amazon Seller Services Private Limited *ASSPL-Amazon Seller Services Pvt. Ltd., ARIPL-Amazon Retail India Pvt. Ltd. (only where Amazon Retail India Pvt. Ltd. fulfillment center is co-located) Customers desirous of availing input GST credit are requested to create a Business account and purchase on Amazon.in/business from Business eligible offersPage 1 of 1
--------------------------------------------------
TYPE: NarrativeText
TEXT:
For Amazon Seller Services Private Limited:Authorized SignatoryOrder Number: 402-6064414-6979531Invoice Number : MKT-101195176Order Date: 23.05.2026Invoice Details : KA-BLR8-1044-2627Invoice Date : 23.05.2026Sl. NoDescriptionUnit PriceQtyNet AmountTax RateTax TypeTax AmountTotal Amount1Marketplace Fees ₹3.95₹3.959%CGST₹0.35₹4.659%SGST₹0.35TOTAL:₹0.70₹4.65Amount in Words:Four Point Six Five only(1) Service Accounting Code: 998319Whether tax is payable under reverse charge - NoPayment Transaction ID: i93r4Gnk2nsPvg5eCtHS2PQNseuwPBcSEivDate & Time: 23/05/2026, 09:01:23hrsInvoice Value: 4.65Mode of Payment: UPISignature validDigitally signed by DS AMAZON SELLER SERVICES PRIVATE LIMITED 6Date: 2026.05.23 07:44:47 UTC Reason: Invoice Sold By :Amazon Seller Services Private Limited *Sattva Horizon, Survey No 6/1 and 7/1, VinayakNagar, KattigenahalliVenkatala Village, Yelahanka HobliBangalore, Karnataka – 560064IndiaPAN No: AAICA3918JGST Registration No: 29AAICA3918J1ZECIN No: U51900KA2010PTC053234Billing Address :Jesna AugustineFlat No. 211, No. 77 East,, Phase -2, CozyhomeLayoutBENGALURU, KARNATAKA, 562125INState/UT Code: 29Shipping Address :Jesna Augustine Jesna AugustineFlat No. 211, No. 77 East,, Phase -2, CozyhomeLayoutBENGALURU, KARNATAKA, 562125INState/UT Code: 29 Place of supply: KARNATAKAPlace of delivery: KARNATAKA
--------------------------------------------------

In [11]:
import fitz

doc = fitz.open("/Users/libinvarghese/Documents/Jesna/projects/personal_finacial_assistant/plan_your_budget/data/raw/2dbddc56-6977-4ced-9777-4447dba9b247_invoice.pdf")

page = doc[0]

text = page.get_text()

print(text)

Tax Invoice/Bill of Supply/Cash Memo
(Original for Recipient)
*ASSPL-Amazon Seller Services Pvt. Ltd., ARIPL-Amazon Retail India Pvt. Ltd. (only where Amazon Retail India Pvt. Ltd. fulfillment center is co-located)
Customers desirous of availing input GST credit are requested to create a Business account and purchase on Amazon.in/business from Business eligible offers
Please note that this invoice is not a demand for payment
Page 1 of 1
For Shroff Publishers & Distributors Pvt. Ltd.:
Authorized Signatory
Order Number: 402-6064414-6979531
Invoice Number : BLR8-79575
Order Date: 23.05.2026
Invoice Details : KA-BLR8-179368921-2627
Invoice Date : 23.05.2026
Sl.
No Description
Unit Price Discount Qty Net
Amount
Tax
Rate
Tax
Type
Tax
Amount
Total
Amount
1
Generative AI System Design Interview (Full
Colour Edition) | 9355424965 ( 9789355424969 )
HSN:49011010
₹1,900.00 ₹0.00
1 ₹1,900.00 0% IGST ₹0.00 ₹1,900.00
0% CGST ₹0.00
0% None ₹0.00
0% SGST ₹0.00
Shipping Charges
₹79.00
-₹79.00
₹0.00
0% IGST ₹0.00
₹0.00
0% CGST ₹0.00
0% None ₹0.00
0% SGST ₹0.00
TOTAL:
₹0.00 ₹1,900.00
Amount in Words:
One Thousand Nine Hundred only
Whether tax is payable under reverse charge - No
Sold By :
Shroff Publishers & Distributors Pvt. Ltd.
*
Building 2 ( Wh 2), Plot no. 12/P2 (IT Sector),
Hitech, Defence and Aerospace Park, Devanahalli
Bengaluru, Karnataka, 562149
IN
PAN No: AAACS9274P
GST Registration No: NotApplicable
Billing Address :
Jesna Augustine
Flat No. 211, No. 77 East,, Phase -2, Cozyhome
Layout
BENGALURU, KARNATAKA, 562125
IN
State/UT Code: 29
Shipping Address :
Jesna Augustine
Jesna Augustine
Flat No. 211, No. 77 East,, Phase -2, Cozyhome
Layout
BENGALURU, KARNATAKA, 562125
IN
State/UT Code: 29
Place of supply: KARNATAKA
Place of delivery: KARNATAKA

In [12]:
import camelot

tables = camelot.read_pdf(
    "/Users/libinvarghese/Documents/Jesna/projects/personal_finacial_assistant/plan_your_budget/data/raw/2dbddc56-6977-4ced-9777-4447dba9b247_invoice.pdf",
    pages="all"
)

print(tables)

<TableList n=2>

In [14]:
df = tables[0].df
import pandas as pd
data =pd.DataFrame(df)
data.head()

,0,1,2,3,4,5,6,7,8,9
0,Sl.\nNo,Description,,Unit Price Discount Qty,,Net\nAmount,Tax\nRate,Tax\nType,Tax\nAmount,Total\nAmount
1,1,Generative AI System Design Interview (Full\nC...,"₹1,900.00\n₹79.00",₹0.00\n-₹79.00,1,₹0.00,"₹1,900.00 0% IGST",0% CGST\n0% None\n0% SGST\n0% IGST\n0% CGST\n0...,₹0.00\n₹0.00\n₹0.00\n₹0.00\n₹0.00\n₹0.00\n₹0.0...,"₹1,900.00\n₹0.00"
2,TOTAL:,,,,,,,,,"₹0.00 ₹1,900.00"
3,Amount in Words:\nOne Thousand Nine Hundred only,,,,,,,,,
4,For Shroff Publishers & Distributors Pvt. Ltd....,,,,,,,,,

In [23]:
import pdfplumber

with pdfplumber.open("/Users/libinvarghese/Documents/Jesna/projects/personal_finacial_assistant/plan_your_budget/data/raw/2dbddc56-6977-4ced-9777-4447dba9b247_invoice.pdf") as pdf:

    for page in pdf.pages:

        tables = page.extract_tables()

        data =pd.DataFrame(tables)
        break
 
data.head()

,0,1,2,3,4
0,"[Sl.\nNo, Description, Unit Price, Discount, Q...","[1, Generative AI System Design Interview (Ful...","[TOTAL:, None, None, None, None, None, None, N...",[Amount in Words:\nOne Thousand Nine Hundred o...,[For Shroff Publishers & Distributors Pvt. Ltd...

In [25]:
doc = fitz.open("/Users/libinvarghese/Documents/Jesna/projects/personal_finacial_assistant/plan_your_budget/data/raw/2dbddc56-6977-4ced-9777-4447dba9b247_invoice.pdf")

page = doc[0]

words = page.get_text('words')

In [26]:
rows = {}

for word in words:

    x0, y0, x1, y1, text, *_ = word

    row_key = round(y0)

    if row_key not in rows:
        rows[row_key] = []

    rows[row_key].append((x0, text))

In [27]:
for row in rows.values():

    row.sort(key=lambda x: x[0])

    print([text for _, text in row])

['Tax', 'Invoice/Bill', 'of', 'Supply/Cash', 'Memo']
['(Original', 'for', 'Recipient)']
['*ASSPL-Amazon', 'Seller', 'Services', 'Pvt.', 'Ltd.,', 'ARIPL-Amazon', 'Retail', 'India', 'Pvt.', 'Ltd.', '(only', 'where', 'Amazon', 'Retail', 'India', 'Pvt.', 'Ltd.', 'fulfillment', 'center', 'is', 'co-located)']
['Customers', 'desirous', 'of', 'availing', 'input', 'GST', 'credit', 'are', 'requested', 'to', 'create', 'a', 'Business', 'account', 'and', 'purchase', 'on', 'Amazon.in/business', 'from', 'Business', 'eligible', 'offers']
['Please', 'note', 'that', 'this', 'invoice', 'is', 'not', 'a', 'demand', 'for', 'payment']
['Page', '1', 'of', '1']
['For', 'Shroff', 'Publishers', '&', 'Distributors', 'Pvt.', 'Ltd.:']
['Authorized', 'Signatory']
['Order', 'Number:', '402-6064414-6979531', 'Invoice', 'Number', ':', 'BLR8-79575']
['Order', 'Date:', '23.05.2026', 'Invoice', 'Details', ':', 'KA-BLR8-179368921-2627']
['Invoice', 'Date', ':', '23.05.2026']
['Sl.', 'Net', 'Tax', 'Tax', 'Tax', 'Total']
['No', 'Amount', 'Rate', 'Type', 'Amount', 'Amount']
['Description', 'Unit', 'Price', 'Discount', 'Qty']
['1']
['Generative', 'AI', 'System', 'Design', 'Interview', '(Full']
['Colour', 'Edition)', '|', '9355424965', '(', '9789355424969', ')', '₹1,900.00', '₹0.00', '1', '₹1,900.00', '0%', 'IGST', '₹0.00', '₹1,900.00']
['HSN:49011010']
['0%', 'CGST', '₹0.00']
['0%', 'None', '₹0.00']
['0%', 'SGST', '₹0.00']
['Shipping', 'Charges', '₹79.00', '-₹79.00', '₹0.00', '0%', 'IGST', '₹0.00', '₹0.00']
['0%', 'CGST', '₹0.00']
['0%', 'None', '₹0.00']
['0%', 'SGST', '₹0.00']
['TOTAL:']
['₹0.00', '₹1,900.00']
['Amount', 'in', 'Words:']
['One', 'Thousand', 'Nine', 'Hundred', 'only']
['Whether', 'tax', 'is', 'payable', 'under', 'reverse', 'charge', '-', 'No']
['Sold', 'By', ':', 'Billing', 'Address', ':']
['Shroff', 'Publishers', '&', 'Distributors', 'Pvt.', 'Ltd.', 'Jesna', 'Augustine']
['*']
['Building', '2', '(', 'Wh', '2),', 'Plot', 'no.', '12/P2', '(IT', 'Sector),']
['Hitech,', 'Defence', 'and', 'Aerospace', 'Park,', 'Devanahalli']
['Bengaluru,', 'Karnataka,', '562149']
['IN']
['PAN', 'No:']
['AAACS9274P']
['GST', 'Registration', 'No:', 'NotApplicable']
['Flat', 'No.', '211,', 'No.', '77', 'East,,', 'Phase', '-2,', 'Cozyhome']
['Layout']
['BENGALURU,', 'KARNATAKA,', '562125']
['IN']
['State/UT', 'Code:', '29']
['Shipping', 'Address', ':']
['Jesna', 'Augustine']
['Jesna', 'Augustine']
['Flat', 'No.', '211,', 'No.', '77', 'East,,', 'Phase', '-2,', 'Cozyhome']
['Layout']
['BENGALURU,', 'KARNATAKA,', '562125']
['IN']
['State/UT', 'Code:', '29']
['Place', 'of', 'supply:', 'KARNATAKA']
['Place', 'of', 'delivery:', 'KARNATAKA']